version: '2.4'

networks:
  test-net:

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_SECRET: ${POSTGRES_SECRET}
    ports:
      - 5432:5432
    networks:
      - test-net
    # labels:
      # - dcw.tasks.*.db_user=test
      # - dcw.tasks.*.db_password=test
      # - dcw.tasks.*.db_name=test
      # - dcw.tasks.init_db=true
      # - dcw.tasks.init_schema.db_name=testdb
      
