apiVersion: v1
kind: Service
metadata:
  annotations:
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f ./hacking/k8s.test-svc-web-app-server.yml.tmp.yml
      --stdout
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-server
  name: web-app-server
  namespace: default
spec:
  ports:
  - name: '8081'
    port: 8081
    targetPort: 80
  selector:
    io.kompose.service: web-app-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f ./hacking/k8s.test-svc-web-app-server.yml.tmp.yml
      --stdout
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-server
  name: web-app-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app-server
  strategy: {}
  template:
    metadata:
      annotations:
        dcw.svc_groups: web-apps,full
        kompose.cmd: kompose convert -f ./hacking/k8s.test-svc-web-app-server.yml.tmp.yml
          --stdout
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/hacking-check-net: 'true'
        io.kompose.service: web-app-server
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: whost
        - name: DB_PASS
          value: siguran
        - name: DB_USER
          value: user
        - name: run.profile
          value: dev
        image: web-app-server
        name: web-app-server
        ports:
        - containerPort: 80
          hostPort: 8081
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
