---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o example.yaml
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (9d8dcb518)
    random-label: random-value
    rich-kompose.service.loadbalancerip: 10.10.10.11
  creationTimestamp: null
  labels:
    io.kompose.service: db-tcp
  name: db-tcp
  namespace: default
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: db
  type: LoadBalancer
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o example.yaml
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (9d8dcb518)
    random-label: random-value
    rich-kompose.service.loadbalancerip: 10.10.10.11
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o example.yaml
        kompose.image-pull-policy: Never
        kompose.service.type: loadbalancer
        kompose.version: 1.30.0 (9d8dcb518)
        random-label: random-value
        rich-kompose.service.loadbalancerip: 10.10.10.11
      creationTimestamp: null
      labels:
        io.kompose.network/example-local-test-net: "true"
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_SECRET
              value: testsecret
            - name: POSTGRES_USER
              value: postgres
          image: postgres:9.6
          imagePullPolicy: Never
          name: db
          ports:
            - containerPort: 5432
              hostPort: 5432
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o example.yaml
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o example.yaml
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/example-local-test-net: "true"
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MY_VAR
              value: my-service
          image: nginx:1.17.8-alpine
          name: web
          resources: {}
      restartPolicy: Always
status: {}

