apiVersion: v1
kind: Service
metadata:
  annotations:
    dcw.kompose.namespace: checker
    dcw.kompose.service.loadbalancerip: 10.10.10.10
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-client
  name: web-app-client
  namespace: checker
spec:
  loadBalancerIP: 10.10.10.10
  ports:
  - name: '8080'
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: web-app-client
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    dcw.kompose.namespace: checker
    dcw.kompose.service.loadbalancerip: 10.10.10.10
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-server
  name: web-app-server
  namespace: checker
spec:
  loadBalancerIP: 10.10.10.10
  ports:
  - name: '8081'
    port: 8081
    targetPort: 80
  selector:
    io.kompose.service: web-app-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dcw.kompose.namespace: checker
    dcw.kompose.service.loadbalancerip: 10.10.10.10
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-client
  name: web-app-client
  namespace: checker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app-client
  strategy: {}
  template:
    metadata:
      annotations:
        dcw.kompose.namespace: checker
        dcw.kompose.service.loadbalancerip: 10.10.10.10
        dcw.svc_groups: web-apps,full
        kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-checker-check-net: 'true'
        io.kompose.service: web-app-client
    spec:
      containers:
      - env:
        - name: ACCESS_KEY
          value: '13121312'
        - name: RUNTIME_ENV
          value: dev
        - name: SECRET_KEY
        - name: run.profile
          value: dev
        image: web-app-client:latest
        name: web-app-client
        ports:
        - containerPort: 8080
          hostPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    dcw.kompose.namespace: checker
    dcw.kompose.service.loadbalancerip: 10.10.10.10
    dcw.svc_groups: web-apps,full
    kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web-app-server
  name: web-app-server
  namespace: checker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web-app-server
  strategy: {}
  template:
    metadata:
      annotations:
        dcw.kompose.namespace: checker
        dcw.kompose.service.loadbalancerip: 10.10.10.10
        dcw.svc_groups: web-apps,full
        kompose.cmd: kompose convert -f hacking/k8s-checker/web-apps.yml.tmp.yml --stdout
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/k8s-checker-check-net: 'true'
        io.kompose.service: web-app-server
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: whost
        - name: DB_PASS
          value: siguran
        - name: DB_USER
          value: user
        - name: run.profile
          value: dev
        image: web-app-server
        name: web-app-server
        ports:
        - containerPort: 80
          hostPort: 8081
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
