apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (HEAD)
    random-label: random-value
    rich-kompose.service.loadbalancerip: 10.10.10.11
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.image-pull-policy: Never
        kompose.service.type: loadbalancer
        kompose.version: 1.30.0 (HEAD)
        random-label: random-value
        rich-kompose.service.loadbalancerip: 10.10.10.11
      creationTimestamp: null
      labels:
        io.kompose.network/example-local-test-net: 'true'
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_SECRET
          value: testsecret
        - name: POSTGRES_USER
          value: postgres
        image: postgres:9.6
        imagePullPolicy: Never
        name: db
        ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
