db:
  environment:
    POSTGRES_DB: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_SECRET: testsecret
    POSTGRES_USER: postgres
  image: postgres:9.6
  labels:
    kompose.image-pull-policy: Neverc
  networks:
  - test-net
  ports:
  - 5432:5432
web:
  environment:
    MY_VAR: my-service
  image: nginx:1.17.8-alpine
  labels: {}
  networks:
  - test-net
  ports: []
