apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/example-local-test-net: 'true'
        io.kompose.service: web
    spec:
      containers:
      - env:
        - name: MY_VAR
          value: my-service
        image: nginx:1.17.8-alpine
        name: web
        resources: {}
      restartPolicy: Always
status: {}
