apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s
    kompose.image-pull-policy: Never
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (HEAD)
    random-label: random-value
    rich-kompose.service.loadbalancerip: 10.10.10.11
  creationTimestamp: null
  labels:
    io.kompose.service: db-tcp
  name: db-tcp
  namespace: default
spec:
  loadBalancerIP: 10.10.10.11
  ports:
  - name: '5432'
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: db
  type: LoadBalancer
status:
  loadBalancer: {}
